# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.0.1
_src_path: https://github.com/GreyTeardrop/private-copier-template
project_name: from-private-template

#copier updated